apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: lastyearproject/dockerapps:vote1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    service: vote
spec:
  selector:
    app: vote
  ports:
  - port: 5000
    targetPort: 5000